### ISSUE TITLE
Authentication window fail with Pywebview 3.6.x

### ISSUE THREAD

**Issue by ivanfdez** [simonrob/email-oauth2-proxy#10]
With pywebview 3.6.x autentication window fails, if I force version 3.5 it works correctly

Authorisation request received for example@gmail.com
[pywebview] loaded event is deprecated and will be removed in 4.0. Use events.loaded instead
An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\user\email-proxy\email-oauth2-proxy\env\lib\site-packages\pystray\_win32.py", line 401, in _dispatcher
    return int(icon._message_handlers.get(
  File "C:\Users\user\email-proxy\email-oauth2-proxy\env\lib\site-packages\pystray\_win32.py", line 213, in _on_notify
    descriptors[index - 1](self)
  File "C:\Users\user\email-proxy\email-oauth2-proxy\env\lib\site-packages\pystray\_base.py", line 306, in inner
    callback(self)
  File "C:\Users\user\email-proxy\email-oauth2-proxy\env\lib\site-packages\pystray\_base.py", line 431, in __call__
    return self._action(icon, self)
  File "C:\Users\user\email-proxy\email-oauth2-proxy\emailproxy.py", line 1252, in authorise_account
    self.create_authorisation_window(request)
  File "C:\Users\user\email-proxy\email-oauth2-proxy\emailproxy.py", line 1276, in create_authorisation_window
    authorisation_window.loaded += self.authorisation_window_loaded
AttributeError: can't set attribute

**Comment by sejtam** [comment]
II have the same issue and the fallback to 3.5 works

**Comment by simonrob** [comment]
Thanks for reporting - this is fixed in ea2fda1.
