### ISSUE TITLE
Not working on ubuntu without desktop?

### ISSUE THREAD

**Issue by JensHoRi** [simonrob/email-oauth2-proxy#144]
Saw this repo and tried out. My system is ubuntu 22.04.1 LTS without grafical desktop.

While starting the proxy I got:

`Traceback (most recent call last):
  File "/usr/local/share/email-oauth2-proxy/emailproxy.py", line 71, in <module>
    import pystray  # the menu bar/taskbar GUI
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 28, in appindicator
    from . import _appindicator as backend; return backend
  File "/usr/local/lib/python3.10/dist-packages/pystray/_appindicator.py", line 19, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
`

Do I interpretate right, proxy requires grafical system?

Would it be possible to configure something like system=(console|desktop) to make it work on console only system?

**Comment by simonrob** [comment]
Please take a look at the readme – you need the `--no-gui` option.
