### ISSUE TITLE
No module named 'timeago.locales.en_short'

### ISSUE THREAD

**Issue by migozz** [simonrob/email-oauth2-proxy#149]
After login, when `access_token_expiry` and `last_activity` written into log file, program will not work.

```
Traceback (most recent call last):
  File "timeago\locales\__init__.py", line 25, in timeago_template
ModuleNotFoundError: No module named 'timeago.locales.en_short'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emailproxy.py", line 2939, in <module>
  File "emailproxy.py", line 2173, in __init__
  File "pystray\_base.py", line 212, in run
  File "pystray\_win32.py", line 123, in _run
  File "pystray\_base.py", line 306, in _mark_ready
  File "pystray\_base.py", line 271, in update_menu
  File "pystray\_win32.py", line 106, in _update_menu
  File "pystray\_win32.py", line 263, in _create_menu
  File "pystray\_base.py", line 639, in __bool__
  File "pystray\_base.py", line 678, in _visible_items
  File "pystray\_base.py", line 676, in strip_tail
  File "pystray\_base.py", line 661, in cleaned
  File "pystray\_base.py", line 502, in visible
  File "pystray\_base.py", line 624, in visible
  File "pystray\_base.py", line 639, in __bool__
  File "pystray\_base.py", line 678, in _visible_items
  File "pystray\_base.py", line 616, in items
  File "emailproxy.py", line 2334, in create_config_menu
  File "emailproxy.py", line 2373, in get_last_activity
  File "timeago\__init__.py", line 80, in format
  File "timeago\locales\__init__.py", line 29, in timeago_template
ModuleNotFoundError: No module named 'timeago.locales.en'
[16160] Failed to execute script 'emailproxy' due to unhandled exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "timeago\locales\__init__.py", line 25, in timeago_template
ModuleNotFoundError: No module named 'timeago.locales.en_short'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "pystray\_base.py", line 394, in setup_handler
  File "emailproxy.py", line 2849, in post_create
  File "emailproxy.py", line 2775, in load_and_start_servers
  File "pystray\_base.py", line 271, in update_menu
  File "pystray\_win32.py", line 106, in _update_menu
  File "pystray\_win32.py", line 263, in _create_menu
  File "pystray\_base.py", line 639, in __bool__
  File "pystray\_base.py", line 678, in _visible_items
  File "pystray\_base.py", line 676, in strip_tail
  File "pystray\_base.py", line 661, in cleaned
  File "pystray\_base.py", line 502, in visible
  File "pystray\_base.py", line 624, in visible
  File "pystray\_base.py", line 639, in __bool__
  File "pystray\_base.py", line 678, in _visible_items
  File "pystray\_base.py", line 616, in items
  File "emailproxy.py", line 2334, in create_config_menu
  File "emailproxy.py", line 2373, in get_last_activity
  File "timeago\__init__.py", line 80, in format
  File "timeago\locales\__init__.py", line 29, in timeago_template
ModuleNotFoundError: No module named 'timeago.locales.en'
Exception ignored in: <function Icon.__del__ at 0x0000000003A0B790>
Traceback (most recent call last):
  File "pystray\_win32.py", line 52, in __del__
AttributeError: 'Icon' object has no attribute '_thread'
```

**Comment by simonrob** [comment]
This is because the workaround for [this `timeago` issue](https://github.com/hustcc/timeago/issues/40) mistakenly imports `en` rather than `en_short`. The [build script](https://github.com/simonrob/email-oauth2-proxy/blob/pyinstaller-build/.github/workflows/pyinstaller.yml) will be updated for the next release; until then you should be able to build a fixed version from the main branch.
