### ISSUE TITLE
o365 shared mailbox - authorization woes

### ISSUE THREAD

**Issue by MrNeuman** [simonrob/email-oauth2-proxy#19]
Hello - struggling to get shared mailbox on o365 authorized.  If I attempt to authorize account in local python window - it sits and spins after I submit creds to o365.  Suspect this is related to our tenant being fully federated.  O365 login should redirect to our on-prem IDP for credential challenge/authorization under normal circumstances.  This redirect never happens in the local python window.  If i use external window I can get a return code generated - but when I submit resulting URL to proxy I get an auth success followed by 400 errors:

2022-03-31 16:35:35,329: Authorisation request received for xxxx (interactive mode)
2022-03-31 16:36:29,137: Successfully authorised request for xxxx
2022-03-31 16:36:29,590: Caught exception while requesting OAuth 2.0 credentials: <HTTPError 400: 'Bad Request'>
2022-03-31 16:36:29,590: IMAP ('127.0.0.1', 52742) <-- b'aaab NO LOGIN Email OAuth 2.0 Proxy: Login failure - saved authentication data invalid for account xxxx\r\n'
2022-03-31 16:36:29,606: IMAP ('127.0.0.1', 52742) <-- b'* BYE Autologout; authentication failed\r\n'

Config file doesn't get updated with any token values.

Shared account is enabled such that it can login directly to o365 - so delegation should not be necessary to best of my knowledge.  This is how the account is used with IMAP today.

Thank you.

**Comment by simonrob** [comment]
The first thing I'd try here would be to verify that the proxy is working. Can you set it up successfully with a non-delegate account? If that succeeds, what happens when you set up the delegate account but authenticate with an account that has been granted access rather than the delegate account itself? If that is also successful, does [this situation](https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/accessing-shared-mailboxes-fails) apply?

I don't have a test delegate account where direct login is enabled, so I can't test this myself. If you are still unable to get it working, could you provide a test account?

**Comment by MrNeuman** [comment]
In testing with a regular mailbox...

windows 2019 server
python 3.8.10

result when attempting to authorize account in native app (same result with 32bit or 64 bit python install):

Unhandled Exception: Python.Runtime.PythonException: MissingManifestResourceException : Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Toolkit.Win32.UI.Controls.DesignerUI.resources" was correctly embedded or linked into assembly "Microsoft.Toolkit.Forms.UI.Controls.WebView" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.Toolkit.Win32.UI.Controls.DesignerUI.get_E_NOTSUPPORTED_OS_RS4()
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.OSVersionHelper.ThrowIfBeforeWindows10April2018()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

resulting in proxy crash.

result when attempting to authorize external (32bit python):

2022-04-01 10:58:01: Successfully authorised request for xxxx
2022-04-01 10:58:01: Caught exception while requesting OAuth 2.0 credentials: <HTTPError 401: 'Unauthorized'>
2022-04-01 10:58:01: IMAP ('172.28.1.38', 54915) <-- b'aaab NO LOGIN Email OAuth 2.0 Proxy: Login failure - saved authentication data invalid for account xxxx\r\n'
2022-04-01 10:58:01: IMAP ('172.28.1.38', 54915) --> [ Client disconnected ]
2022-04-01 10:58:01: IMAP ('172.28.1.38', 54915) <-- b'* BYE Autologout; authentication failed\r\n'
error: uncaptured python exception, closing channel <__main__.IMAPOAuth2ClientConnection 172.28.1.38:54915 at 0x3b96a00> (<class 'OSError'>:[WinError 10038] An operation was attempted on something that is not a socket [C:\tools\Python\Python38-32\lib\asyncore.py|read|83] [C:\tools\Python\Python38-32\lib\asyncore.py|handle_read_event|420] [emailproxy.py|handle_read|555] [emailproxy.py|process_data|612] [emailproxy.py|authenticate_connection|650] [emailproxy.py|send|563] [C:\tools\Python\Python38-32\lib\asyncore.py|send|527] [C:\tools\Python\Python38-32\lib\asyncore.py|initiate_send|514] [C:\tools\Python\Python38-32\lib\asyncore.py|send|358])
2022-04-01 10:58:01: IMAP ('172.28.1.38', 54915) --> [ Client disconnected ]

result when attempting to authorize external (64bit python):

2022-04-01 11:13:34: Successfully authorised request for xxxx
2022-04-01 11:13:35: Caught exception while requesting OAuth 2.0 credentials: <HTTPError 400: 'Bad Request'>
2022-04-01 11:13:35: IMAP ('172.28.1.38', 54976) <-- b'aaab NO LOGIN Email OAuth 2.0 Proxy: Login failure - saved authentication data invalid for account xxxx\r\n'
2022-04-01 11:13:35: IMAP ('172.28.1.38', 54976) <-- b'* BYE Autologout; authentication failed\r\n'


Will attempt with newer release of python but had fits with pythonnet yesterday on newer releases.

**Comment by simonrob** [comment]
Thanks for following up. The first log is I suspect related to pythonnet, which is required to show the popup window, but as you note can be a pain to install properly. I think we can ignore this for now.

It's strange that the second two logs are different – the version of python that you're using shouldn't make a difference here, and in particular the fact that you get a different HTTP error (401 vs. 400) is very odd. What happens if you try the `--local-server-auth` option?

If that still doesn't work, could you try, say, a Gmail account instead? This would help verify whether the issue is something particular to your authentication/authorisation setup, or a more general issue with the proxy.

**Comment by MrNeuman** [comment]
With --local-server-auth - 64bit:

2022-04-01 11:41:48: Authorisation request received for xxxx (local server auth mode)
Exception in thread EmailOAuth2Proxy-auth-xxxx:
Traceback (most recent call last):
  File "C:\tools\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\tools\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "emailproxy.py", line 344, in start_redirection_receiver_server
    Log.debug('Local server auth mode (%s:%d): starting server to listen for authentication response' % (
TypeError: %d format: a number is required, not NoneType

**Comment by simonrob** [comment]
Ok, this is an unrelated issue, caused because you haven't specified a port for `redirect_uri`. The default value for this attribute in the configuration file is `http://localhost`, but when using this mode you need to also specify a port number (or run via `sudo`) in order to allow the proxy to actually start a server. This is [documented in the configuration file](https://github.com/simonrob/email-oauth2-proxy/blob/e032e4ce03196a8966db3c36e1662eb89ba415dc/emailproxy.config#L53), but in 4563a5e I've made the error message clearer.

What happens if you change to `redirect_uri = http://localhost:8080` ?

**Comment by MrNeuman** [comment]
Thank you - unfortunately I get basically the same result.

2022-04-01 12:18:28: Please visit the following URL <http://myo365url>
2022-04-01 12:19:30: Local server auth mode (localhost:8080): received authentication response GET /?code=xxxxx HTTP/1.1 200 118
2022-04-01 12:19:30: Local server auth mode (localhost:8080): closing local server and returning response http://localhost:8080/?code=xxxxx
2022-04-01 12:19:30: Caught exception while requesting OAuth 2.0 credentials: <HTTPError 401: 'Unauthorized'>
2022-04-01 12:19:30: IMAP ('172.28.1.38', 55200) <-- b'aaab NO LOGIN Email OAuth 2.0 Proxy: Login failure - saved authentication data invalid for account xxxx\r\n'
2022-04-01 12:19:30: IMAP ('172.28.1.38', 55200) <-- b'* BYE Autologout; authentication failed\r\n'

**Comment by MrNeuman** [comment]
Disregard - think I grabbed logs from an earlier test - will regroup and try again.

**Comment by simonrob** [comment]
In that case I think the best thing to do is try a Gmail account to check the proxy is working with your setup.

The error you are getting suggests that for whatever reason, despite successfully authenticating, the token request is failing. Is there any configuration on your O365 setup that might cause this?

**Comment by MrNeuman** [comment]
I'm not in a position to test with Gmail and ultimately that isn't my use case - but I understand the ask.  As far as our o365 the only thing I can think of that may be in play is the federation - but that seems to only be a concern for the native PY browser window.  I can use external authorization and make progress - but it breaks down on submitting the return code to the proxy.  I see the corresponding sign-ins for the application in Azure AD - so seemingly good up to that point.  I will see about creating a cloud-only mailbox account to try and eliminate that angle.

**Comment by simonrob** [comment]
Are you using a client ID/secret that you have created yourself, or one from another client? Just wondering whether its scope is correct.

Could you provide a test account somehow, so that I can look into the issue?

**Comment by MrNeuman** [comment]
Registered a new o365 app in Azure AD for the proxy with a redirect endpoint of http://localhost.  Created a client secret within the app.  Entered corresponding values for client_id and client_secret in proxy config.  If I view the corresponding Enterprise App in Azure AD - I see the following for permissions with my mailboxes as consented users.

![image](https://user-images.githubusercontent.com/102765829/161322145-48c93a68-4db5-42cb-affc-67d1ebadf6f9.png)

**Comment by simonrob** [comment]
What happens if you walk through the process of authenticating and retrieving a token manually using the values you're providing to the proxy? Microsoft has an interactive guide [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow).

You can see the parameters the proxy uses for the code request in the external auth link you've been successfully using, and the subsequent token request is [here](https://github.com/simonrob/email-oauth2-proxy/blob/4563a5e9a4d1abcf17e2ed865611dabf9c2ddfd3/emailproxy.py#L445). Is there something missing that is required by your setup?

**Comment by MrNeuman** [comment]
Getting there...

Opened the Postman sample from the MS link - updated 'token request - auth code' with my tenant/app specific values and code obtained from a separate browser session and here's resulting 401 error displayed in Postman:

{
    "error": "invalid_client",
    "error_description": "AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented.\r\nTrace ID: acd7632c-7437-4dcd-b5af-4cd1db7c5500\r\nCorrelation ID: bbbcb06f-7774-49b3-a551-adc683e78cfd\r\nTimestamp: 2022-04-01 20:00:22Z",
    "error_codes": [
        700025
    ],
    "timestamp": "2022-04-01 20:00:22Z",
    "trace_id": "acd7632c-7437-4dcd-b5af-4cd1db7c5500",
    "correlation_id": "bbbcb06f-7774-49b3-a551-adc683e78cfd"
}

**Comment by simonrob** [comment]
That is intriguing (but encouraging). If you remove `'client_secret': client_secret,` from [this line](https://github.com/simonrob/email-oauth2-proxy/blob/4563a5e9a4d1abcf17e2ed865611dabf9c2ddfd3/emailproxy.py#L454) of the proxy script, does it work?

**Comment by MrNeuman** [comment]
Was able to get to a 200 status code and token issue in Postman after removing/adding the redirect URI.  The app honestly doesn't appear to be any different on surface than it was prior to making changes but will take the win either way.

Thank you for the Postman reference - getting to an actual error message was key.  Wrapping up for day but will revisit in proxy and post back results.

Thank you for this project!

I'm banking on it to prolong the life of the email automation app below as vendor indicated they were taking a 'wait and see' approach to the upcoming end of basic auth by MS.

https://www.glocksoft.com/email-processor/

**Comment by MrNeuman** [comment]
Just to close this out - I was able to complete an authorization in the proxy after the app changes in Azure AD and run an end-to-end test with my imap client.  Thank you for all your help.

**Comment by simonrob** [comment]
That's great - yes, setting up clients can be very error-prone as the configuration options are not well labelled or documented.

Still, it was harder than it needed to be to solve this issue, so in e4c5979 I've made sure the proxy outputs the actual error message to avoid having to manually trace the authentication steps. Hopefully this helps others solve this and similar issues more easily in future.
