### ISSUE TITLE
Proxy crashes when clicking "Authorize Account"

### ISSUE THREAD

**Issue by overcloker55** [simonrob/email-oauth2-proxy#39]
I'm using windows 10 and the proxy detects the authorization request and as soon as I click Authorize account I get this error. I tried with 2 different clients but get the same error.

2022-07-14 15:36:20: SMTP (localhost:2465; 127.0.0.1:62030->smtp.gmail.com:465)     --> b'AUTH XOAUTH2\r\n'
2022-07-14 15:36:20: SMTP (localhost:2465; 127.0.0.1:62030->smtp.gmail.com:465)     <-- b'334 \r\n'
2022-07-14 15:36:20: Authorisation request received for myEmail@gmail.com (interactive mode)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by overcloker55** [comment]
just a follow-up. I tried the telnet method using IMAP but got the exact same error.

**Comment by simonrob** [comment]
This is not a bug in the proxy, but an issue with [`pywebview`](https://pywebview.flowrl.com/) on Windows. The resolution is to install a different version of that module's dependency [`pythonnet`](https://pythonnet.github.io/) (e.g., see [here](https://stackoverflow.com/questions/70640459/) for a similar discussion). You can check your pywebview installation without using the proxy by using the starter code found in the [pywebview usage guide](https://pywebview.flowrl.com/guide/usage.html).

If you are not able to resolve the pywebview issue easily, then the proxy's `--local-server-auth` option is another solution, as it does not use pywebview.
