### ISSUE TITLE
Error with --'no-gui' on Linux without X-server

### ISSUE THREAD

**Issue by gegu** [simonrob/email-oauth2-proxy#54]
Today I tried to run the script with the argument `--no-gui` on a Linux installation without X-server and got the following error on `import pystray`:

```
Traceback (most recent call last):
  File "emailproxy.py", line 39, in <module>
    import pystray
  File "~/emailproxy/.env/lib/python3.7/site-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "~/emailproxy/.env/lib/python3.7/site-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "~/emailproxy/.env/lib/python3.7/site-packages/pystray/__init__.py", line 36, in xorg
    from . import _xorg as backend; return backend
  File "~/emailproxy/.env/lib/python3.7/site-packages/pystray/_xorg.py", line 36, in <module>
    display = Xlib.display.Display()
  File "~/emailproxy/.env/lib/python3.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "~/emailproxy/.env/lib/python3.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "~/emailproxy/.env/lib/python3.7/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "~/emailproxy/.env/lib/python3.7/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "~/emailproxy/.env/lib/python3.7/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
```

I was able to fix the problem by only importing `pystray` when the `--no-gui` argument was not specified.

```py
if not '--no-gui' in sys.argv: import pystray
```

Maybe this will help someone who also tries this.

Thanks for your great project 👍

**Comment by gegu** [comment]
Sorry, I overlooked the branch [requirements-no-gui](https://github.com/simonrob/email-oauth2-proxy/tree/requirements-no-gui).

**Comment by simonrob** [comment]
Thanks for this report. The proxy was originally designed as a GUI-first application given the need for interaction to actually authenticate an account.

Let me know how you get on with the [requirements-no-gui](https://github.com/simonrob/email-oauth2-proxy/tree/requirements-no-gui) branch, which should simplify things in situations like yours – I'm happy to merge this branch if it is useful.

**Comment by simonrob** [comment]
Done

**Comment by gegu** [comment]
`export EMAIL_OAUTH2_PROXY_REQUIREMENTS_NO_GUI=true ; python3 emailproxy.py --no-gui --local-server-auth`

Looks good after initial tests.

Tomorrow I will test more extensively and then report again.

Thanks

**Comment by gegu** [comment]
Work like a charm 👍  Tested under linux (Debian) and windows.
