### ISSUE TITLE
Cannot start emailproxy.py 

### ISSUE THREAD

**Issue by felix138** [simonrob/email-oauth2-proxy#55]
Hi 
I follow ur readme and try to start it on centos 7 , But it got some error information. 
system: CentOS Linux release 7.9.2009 (Core)
Python version: Python 3.6.8
installed pystray: pystray 0.19.4

Traceback (most recent call last):
  File "emailproxy.py", line 39, in <module>
    import pystray
  File "/usr/local/lib/python3.6/site-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "/usr/local/lib/python3.6/site-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/usr/local/lib/python3.6/site-packages/pystray/__init__.py", line 36, in xorg
    from . import _xorg as backend; return backend
  File "/usr/local/lib/python3.6/site-packages/pystray/_xorg.py", line 36, in <module>
    display = Xlib.display.Display()
  File "/usr/local/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.6/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/usr/local/lib/python3.6/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/usr/local/lib/python3.6/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""

From your issue page, I see it needs to install 'gir1.2-ayatanaappindicator3-0.1' package . But it does not support centos 7,
at least , I cannot found rpm package from google . 
. Could you help me to take a look ? thanks .

**Comment by simonrob** [comment]
Please take a look at the new branch discussed in #54. Let me know if this simplifies dependency setup for you?

**Comment by felix138** [comment]
Thanks a lot, this is a great project， it was fixed. Now I can move on
