### ISSUE TITLE
Unable to run proxy as a Linux service

### ISSUE THREAD

**Issue by ebraspen** [simonrob/email-oauth2-proxy#56]
It seems not possible to run the email-oauth2-proxy as a headless service in Linux.
Despite the start-up of the emailproxy.py with option --no-gui and the env variable EMAIL_OAUTH2_PROXY_REQUIREMENTS_NO_GUI=1, the prpograms ends with the following message:
-----8<-----
Traceback (most recent call last):
  File "emailproxy.py", line 39, in <module>
    import pystray
  File "/home/fetch/.local/lib/python3.6/site-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "/home/fetch/.local/lib/python3.6/site-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/home/fetch/.local/lib/python3.6/site-packages/pystray/__init__.py", line 36, in xorg
    from . import _xorg as backend; return backend
  File "/home/fetch/.local/lib/python3.6/site-packages/pystray/_xorg.py", line 36, in <module>
    display = Xlib.display.Display()
  File "/home/fetch/.local/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/fetch/.local/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/fetch/.local/lib/python3.6/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/home/fetch/.local/lib/python3.6/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/home/fetch/.local/lib/python3.6/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: **Bad display name** ""
-----8<-----

The program clearly looks for the DISPLAY variable, which in my non graphical envrion,ent is not set.
What do I miss here?
Thanks for your help.

**Comment by simonrob** [comment]
Is this just with the most recent release (2022-08-22), or do you also get this with the latest commit (which removes the need for the environment variable)

**Comment by simonrob** [comment]
Is this just with the most recent release (2022-08-22), or do you also get this with the latest commit (which removes the need for the environment variable)

**Comment by ebraspen** [comment]
Hi Simon,

I'm using version 2022-07-09. So then do you recommend me to try the commit of today Aug, 29?
Thanks

**Comment by simonrob** [comment]
Yes - it removes the need for the environment variable, and you can just use `--no-gui`.

**Comment by ebraspen** [comment]
Latest build of today installed, which starts successful with just the -no-gui option.
Thanks!
