### ISSUE TITLE
Error when trying to authenticate on Windows10

### ISSUE THREAD

**Issue by dbilewicz** [simonrob/email-oauth2-proxy#69]
Hi, 

When i'm trying to use "authorise account" on Windows i got:

`An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pystray\_win32.py", line 401, in _dispatcher
    return int(icon._message_handlers.get(
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pystray\_win32.py", line 213, in _on_notify
    descriptors[index - 1](self)
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pystray\_base.py", line 324, in inner
    callback(self)
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pystray\_base.py", line 449, in __call__
    return self._action(icon, self)
  File "C:\Users\darek\Desktop\email-oauth2-proxy-main\emailproxy.py", line 1983, in authorise_account
    webview.start(gui=forced_gui, debug=Log.get_level() == logging.DEBUG)
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\webview\__init__.py", line 122, in start
    guilib = initialize(gui)
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\webview\guilib.py", line 101, in initialize
    if not try_import(guis):
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\webview\guilib.py", line 62, in try_import
    if import_func():
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\webview\guilib.py", line 52, in import_winforms
    import webview.platforms.winforms as guilib
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\webview\platforms\winforms.py", line 31, in <module>
    import clr
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Users\darek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pythonnet\__init__.py", line 42, in load
    func = _LOADER_ASSEMBLY["Python.Runtime.Loader.Initialize"]
TypeError: 'Assembly' object is not subscriptable`

I tried this on two Windows 10 instances.

**Comment by simonrob** [comment]
This is discussed in the troubleshooting section of the readme. The Windows packages required to display the authentication pop-up are not yet compatible with Python 3.10. You should be able to resolve this via one of the following options:
- `pip install --pre pythonnet`
- Downgrade to an older Python version
- Use the `--local-server-auth` proxy option

**Comment by simonrob** [comment]
Just to follow up - I see that pythonnet 3.0.0 has just yesterday [been released](https://pypi.org/project/pythonnet/). So, you should be able to resolve this simply via `python -m pip install --upgrade pythonnet`.

Please let me know whether this works – if so, I will update the requirements file accordingly.

**Comment by dbilewicz** [comment]
On python 3.9.13 i have different error: Unhandled exception - Object reference not set to an instance of an object

```

Wyjątek nieobsłużony: System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w System.Windows.Forms.Control.get_CacheTextInternal()
   w System.Windows.Forms.Control.get_Text()
   w System.Windows.Forms.Control.set_Text(String value)
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w Python.Runtime.PythonException.ThrowLastAsClrException()
   w Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   w Python.Runtime.Dispatcher.Dispatch(Object[] args)
   w __System_Threading_ThreadStartDispatcher.Invoke()
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Threading.ThreadHelper.ThreadStart()
```

**Comment by dbilewicz** [comment]
> 

It looks like Registry path is wrong - i have "Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\EdgeUpdate\Clients\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}"

**Comment by dbilewicz** [comment]
I found simmilar issue on pywebview project - https://github.com/r0x0r/pywebview/issues/953 
They say it should work despite this error.

**Comment by HollererJ** [comment]
Have the same issue, the application stops working when the error occurs. 
Is there any workaround ?

**Comment by simonrob** [comment]
I tried just now with Python 3.10.7, pythonnet 3.0.0.post1 and pywebview 3.6.3 – I can replicate the error. However, I also get exactly the same issue using the basic pywebview example, so unfortunately it is an issue with that module. I have reported this as a [new issue](https://github.com/r0x0r/pywebview/issues/961).

**Comment by simonrob** [comment]
d1a7421 temporarily adds a new requirement for Python 3.10 on Windows, which resolves the issue until pywebview is updated. You can also do this manually via:

```shell
python -m pip install clr-loader==0.1.7
python -m pip install pythonnet==3.0.0a2
```

**Comment by dbilewicz** [comment]
> [d1a7421](https://github.com/simonrob/email-oauth2-proxy/commit/d1a7421e36918ac8afb5bcfed2254faffe1c4464) temporarily adds a new requirement for Python 3.10 on Windows, which resolves the issue until pywebview is updated. You can also do this manually via:
> 
> ```shell
> python -m pip install clr-loader==0.1.7
> python -m pip install pythonnet==3.0.0a2
> ```

Correct, that helped. Authorise web window is now vissible and program did not crashed. Thanks alot!

**Comment by yon-y** [comment]
> [d1a7421](https://github.com/simonrob/email-oauth2-proxy/commit/d1a7421e36918ac8afb5bcfed2254faffe1c4464) temporarily adds a new requirement for Python 3.10 on Windows, which resolves the issue until pywebview is updated. You can also do this manually via:
> 
> ```shell
> python -m pip install clr-loader==0.1.7
> python -m pip install pythonnet==3.0.0a2
> ```

That works for me. Thank you!

**Comment by simonrob** [comment]
I'm going to lock this issue but keep it open just as a place to track when to remove the temporary fix (which will be when pywebview 3.6.4 is released).
