### ISSUE TITLE
Authorise account doesn't work fully with Windows Server 2019 (and Python 3.11.0)

### ISSUE THREAD

**Issue by Dan-Karlsson** [simonrob/email-oauth2-proxy#91]
I did an install on a pretty clean Windows Server 2019. I started with installing Python 3.11.0.

When trying to authorise account I got this error:
```
Failed to initialize pythonnet: System.NotSupportedException: Python ABI v3.11.0 is not supported: Searching for Python.Runtime.TypeOffset311, found TypeOffset310,TypeOffset36,TypeOffset37,TypeOffset38,TypeOffset39,TypeOffset.

   at Python.Runtime.Native.ABI.Initialize(Version version)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable\`1 args, Boolean setSysArgv, Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.InitExt()
   at Python.Runtime.Loader.Initialize(IntPtr data, Int32 size)
   at Python.Runtime.Native.ABI.Initialize(Version version)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable\`1 args, Boolean setSysArgv, Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.InitExt()
   at Python.Runtime.Loader.Initialize(IntPtr data, Int32 size)An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pystray\_win32.py", line 401, in _dispatcher
    return int(icon._message_handlers.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pystray\_win32.py", line 213, in _on_notify
    descriptors\[index - 1\](self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pystray\_base.py", line 324, in inner
    callback(self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pystray\_base.py", line 449, in __call__
    return self._action(icon, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\email-oauth2-proxy-main\email-oauth2-proxy-main\emailproxy.py", line 2078, in authorise_account
    webview.start(gui=forced_gui, debug=Log.get_level() == logging.DEBUG)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\__init__.py", line 122, in start
    guilib = initialize(gui)
             ^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\guilib.py", line 101, in initialize
    if not try_import(guis):
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\guilib.py", line 62, in try_import
    if import_func():
       ^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\guilib.py", line 52, in import_winforms
    import webview.platforms.winforms as guilib
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\webview\platforms\winforms.py", line 31, in <module>
    import clr
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pythonnet\__init__.py", line 44, in load
    raise RuntimeError("Failed to initialize Python.Runtime.dll")
RuntimeError: Failed to initialize Python.Runtime.dll
```

After uninstalling Python 3.11 and instead installing Python 3.10.8 I got another error. I installed Edge and if I remember correctly the error message changed a bit, after installing Edge the error message is this:
```
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Runtime Registry path: Computer\HKEY_CURRENT_USER\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Runtime Registry path: Computer\HKEY_LOCAL_MACHINE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Beta Registry path: Computer\HKEY_CURRENT_USER\Microsoft\EdgeUpdate\Clients\{2CD8A007-E189-409D-A2C8-9AF4EF3C72AA}
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Beta Registry path: Computer\HKEY_LOCAL_MACHINE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{2CD8A007-E189-409D-A2C8-9AF4EF3C72AA}
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Developer Registry path: Computer\HKEY_CURRENT_USER\Microsoft\EdgeUpdate\Clients\{0D50BFEC-CD6A-4F9A-964C-C7416E3ACB10}
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Developer Registry path: Computer\HKEY_LOCAL_MACHINE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{0D50BFEC-CD6A-4F9A-964C-C7416E3ACB10}
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Canary Registry path: Computer\HKEY_CURRENT_USER\Microsoft\EdgeUpdate\Clients\{65C35B14-6C1D-4122-AC46-7148CC9D6497}
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Canary Registry path: Computer\HKEY_LOCAL_MACHINE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{65C35B14-6C1D-4122-AC46-7148CC9D6497}
[pywebview] EdgeHTML is deprecated. See https://pywebview.flowrl.com/guide/renderer.html#web-engine on details how to use Edge Chromium

Unhandled Exception: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Toolkit.Win32.UI.Controls.DesignerUI.resources" was correctly embedded or linked into assembly "Microsoft.Toolkit.Forms.UI.Controls.WebView" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.OSVersionHelper.ThrowIfBeforeWindows10April2018()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

When starting it with --external-auth it works. So I'm happy for now. :)

**Comment by simonrob** [comment]
This is an issue with pywebview and pythonnet, and is similar to that discussed in #69. It is not something that the proxy can control or address itself.

Once pywebview has been updated this should be resolved, but you can also follow the instructions in the error message to install a compatible web engine.
